id: daily_sync
enabled: true
apiVersion: v1

trigger:
  type: cron
  cron: "* * * * *"

tasks:
  - id: fetch
    type: core/http.get
    inputs:
      url: https://jsonplaceholder.typicode.com/posts/1

  - id: save
    type: core/console.log
    needs: [fetch]
    inputs:
      message: "{{ tasks.fetch.output }}"